global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:4000']

  - job_name: 'user_service_1'
    static_configs:
      - targets: ['user_service_1:5000']

  - job_name: 'user_service_2'
    static_configs:
      - targets: ['user_service_2:5001']

  - job_name: 'user_service_3'
    static_configs:
      - targets: ['user_service_3:5002']

  - job_name: 'booking_service_1'
    static_configs:
      - targets: ['booking_service_1:5004']

  - job_name: 'booking_service_2'
    static_configs:
      - targets: ['booking_service_2:5005']

  - job_name: 'booking_service_3'
    static_configs:
      - targets: ['booking_service_3:5006']